graph/urls.py
from django.conf.urls.static import static
from django.conf.urls import patterns, url, include
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib import admin
from graph.apps.api.views import SpreadsheetListView, SpreadsheetDetailView, UploadView, ChartMetaView, ChartCreateView, ChartDetailView

admin.autodiscover()

urlpatterns = patterns('',
   # (r'', include('graph.apps.')),
    #url(r'^editor/', TemplateView.as_view(template_name='spreadsheet.html')),
    url(r'^/?$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^new/', UploadView.as_view(), name='spreadsheet-upload'),
    url(r'^ss/?$', SpreadsheetListView.as_view(), name="spreadsheet-list"),
    url(r'^ss/(?P<pk>\d+)?', SpreadsheetDetailView.as_view(), name='spreadsheet-detail'),
    url(r'api/chart/(?P<pk>\d+)/?$', ChartMetaView.as_view(), name='chart-definition'),
    url(r'^api/chart/(?P<pk>\d+)/data/$', 'graph.apps.api.views.xld', name='chart-data'),
    url(r'^api/chart/(?P<pk>\d+)/data/orient/(?P<orient>\w+)/$', 'graph.apps.api.views.xld', name='chart-data-orient'),
    url(r'^api/chart/(?P<pk>\d+)/data/orient/(?P<orient>\w+)/format/(?P<format>\w+)/$', 'graph.apps.api.views.xld', name='chart-data-orient-format'),
    url(r'^chart/new/?$', ChartCreateView.as_view(), name="chart-create"),
    url(r'^chart/(?P<pk>\d+)/?$', ChartDetailView.as_view(), name="chart-detail"),
    url(r'^chart/$', TemplateView.as_view(template_name='chart.html'), name='chart'),
    url(r'^api/nb/(?P<notebook>\w+)/(?P<var>\w+)/?', 'graph.apps.api.views.notebook_visualization', name="notebook-visualization"),
    url(r'^api/nb/$', 'graph.apps.api.views.notebook_list', name="notebook-list"),
    url(r'^api/nb/(?P<notebook>\w+)/$', 'graph.apps.api.views.notebook_var_list', name="notebook-var-list"),
    url(r'^nb/?$', TemplateView.as_view(template_name="notebook_viewer.html"), name="notebook-viewer"),
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG and settings.MEDIA_ROOT:
    urlpatterns += static(settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

graph/apps/api/models.py
from django.db import models
from jsonfield import JSONField

# Create your models here.
class FileData(models.Model):
    file = models.FileField(upload_to=".")
    title = models.CharField(max_length=255, blank=True)
    created_on = models.DateField(auto_now_add=True)
    updated_on = models.DateField(auto_now=True)


class Chart(models.Model):
    CHART_TECH_WIJMO = 'W'
    CHART_TECH_VEGA = 'V'
    CHART_TECH_CHOICES = (
        (CHART_TECH_WIJMO, 'Wijmo'),
        (CHART_TECH_VEGA, 'Vega')
    )

    CHART_TYPE_LINE = 'L'
    CHART_TYPE_BAR = 'B'
    CHART_TYPE_PIE = 'P'
    CHART_TYPE_CHOICES = (
        (CHART_TYPE_LINE, 'Line'),
        (CHART_TYPE_BAR, 'Bar'),
        (CHART_TYPE_PIE, 'Pie')
    )

    tech = models.CharField(max_length=2, choices=CHART_TECH_CHOICES)
    type = models.CharField(max_length=1, choices=CHART_TYPE_CHOICES)
    title = models.CharField(max_length=32)
    data = models.ForeignKey('FileData')
    options = JSONField(blank=True)


class ChartSeries(models.Model):
    chart = models.ForeignKey('Chart', related_name='series')
    column = models.CharField(max_length=32)
    axis = models.CharField(max_length=2)
    label = models.CharField(max_length=32, blank=True)
    filter = models.CharField(max_length=255, blank=True)

graph/apps/api/forms.py
__author__ = 'arun'

from django import forms
from django.forms.models import inlineformset_factory
from .models import FileData, Chart, ChartSeries

class ExcelFileForm(forms.ModelForm):
    class Meta:
        model = FileData
        exclude = ['title']


class ChartForm(forms.ModelForm):
    data = forms.ModelChoiceField(queryset=FileData.objects.all(), widget=forms.HiddenInput())
    #options = forms.CharField(widget=forms.HiddenInput())
    #type = forms.ChoiceField(choices=Chart.CHART_TYPE_CHOICES, widget=forms.RadioSelect())
    class Meta:
        model = Chart
        fields = ['title', 'type', 'data']


class ChartSeriesForm(forms.ModelForm):
    column = forms.ChoiceField(widget=forms.Select())
    axis = forms.ChoiceField(widget=forms.Select())
    class Meta:
        model = ChartSeries
        fields = ['column', 'filter', 'label']

ChartSeriesFormset = inlineformset_factory(Chart, ChartSeries)

graph/apps/api/views.py
from django.shortcuts import render
from django.views.generic import View, FormView, TemplateView, ListView, DetailView, CreateView

from django.conf import settings
from django.core.urlresolvers import reverse, reverse_lazy
from django.shortcuts import redirect

from django.http import Http404, HttpResponseServerError

from rest_framework.views import APIView
from rest_framework.response import Response

import os

from .forms import ExcelFileForm, ChartForm, ChartSeriesFormset
from .models import FileData, Chart
from .serializers import ChartSerializer

# Create your views here.
class UploadView(FormView):
    form_class = ExcelFileForm
    template_name = "upload.html"

    def __init__(self):
        super(self.__class__, self).__init__()
        self.id = None

    def get_success_url(self):
        return reverse('spreadsheet-detail', kwargs={'pk': self.id})

    def form_valid(self, form):
        obj = form.save(commit=True)
        self.id = obj.id
        return super(self.__class__, self).form_valid(form)

class SpreadsheetView(TemplateView):
    template_name = "spreadsheet.html"

    def get_context_data(self, **kwargs):
        ctx = super(self.__class__, self).get_context_data(**kwargs)
        if kwargs['pk']:
            ctx['data'] = FileData.objects.get(pk=kwargs['pk'])
        else:
            ctx['sheets'] = FileData.objects.all()
        return ctx

class SpreadsheetListView(ListView):
    model = FileData
    template_name = "api/spreadsheet_list.html"
    context_object_name = "sheets"

class SpreadsheetDetailView(DetailView):
    template_name = "api/spreadsheet_detail.html"
    context_object_name = "sheet"
    model = FileData

    def get_context_data(self, **kwargs):
        ctx = super(self.__class__, self).get_context_data(**kwargs)
        ctx['chart_form'] = ChartForm(initial={'data': self.object})
        ctx['formset'] = ChartSeriesFormset()
        return ctx

class ChartCreateView(CreateView):
    form_class = ChartForm
    template_name = "api/chart_create.html"

    def get_success_url(self):
        return reverse("chart-detail", kwargs= {'pk':self.object.id} )

    def form_valid(self, form):
        formset = ChartSeriesFormset(self.request.POST)
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super(ChartCreateView, self).form_valid(form)

class ChartDetailView(DetailView):
    template_name = "api/chart_detail.html"
    model = Chart
    context_object_name = "chart"

class ChartMetaView(APIView):
    def get_object(self, pk):
        try:
            return Chart.objects.get(pk=pk)
        except Chart.DoesNotExist:
            raise Http404

    def get(self, request, **kwargs):
        chart = self.get_object(kwargs['pk'])
        serializer = ChartSerializer(chart)
        return Response(serializer.data)

import pandas as pd
from django.http import HttpResponse

def xld(request, pk=None, orient='records', format='json'):
    try:
        obj = FileData.objects.get(pk=pk)
    except Chart.DoesNotExist:
        return Http404

    xf = pd.ExcelFile(obj.file.path)
    xld = xf.parse(xf.sheet_names[0])
    return HttpResponse(xld.to_json(orient=orient, date_format='iso'), content_type="application/json")

def chart_data(request, pk):
    try:
        chart = Chart.objects.get(pk=pk)
    except Chart.DoesNotExist:
        return Http404

    xf = pd.ExcelFile(chart.data.file.path)
    xld = xf.parse(xf.sheet_names[0])
    return HttpResponse(xld.to_json(), content_type="application/json")

def chart_create(request):
    form = ChartForm(request.POST)
    formset = ChartSeriesFormset(request.POST)
    if form.is_valid():
        print "form is valid"

    return redirect("index")

import json
import imp
from glob import glob

def load_notebook(notebook):
    nb_path = os.path.join(settings.ROOT_DIR, "{notebook}.ipynb".format(notebook=notebook))
    if not os.path.exists(nb_path):
        raise Http404
    nb = json.load(open(nb_path))
    code = []
    for cell in nb["worksheets"][0]["cells"]:
        if cell["cell_type"] == "code":
            code.extend([ x if x.endswith("\n") else x + "\n" for x in cell["input"]])
    try:
        nbmod = imp.new_module(notebook)
        exec ''.join(code) in nbmod.__dict__
    except Exception as e:
        return HttpResponseServerError(content=e)

    return nbmod

def notebook_visualization(request, notebook, var):
    nbmod = load_notebook(notebook)
    if type(nbmod) == HttpResponseServerError:
        return nbmod

    try:
        return HttpResponse(nbmod.__dict__[var].to_json(), content_type="application/json")
    except KeyError:
        raise Http404

from os.path import join, basename
def notebook_list(request):
    return HttpResponse(json.dumps([basename(path).split(".")[0] for path in glob(join(settings.ROOT_DIR, "*.ipynb"))]), content_type="application/json")

from vincent.visualization import Visualization

def notebook_var_list(request, notebook):
    nbmod = load_notebook(notebook)
    if type(nbmod) == HttpResponseServerError:
        return nbmod
    visualization_vars = []
    for name, var in nbmod.__dict__.iteritems():
        if isinstance(var, Visualization):
            visualization_vars.append(name)

    return HttpResponse(json.dumps(visualization_vars), content_type="application/json")

graph/templates/api/chart_create.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>

graph/templates/api/chart_detail.html
{% extends 'base.html' %}

{% load jsonify %}

{% block extra_head %}
<!--jQuery References-->
<script src="http://code.jquery.com/jquery-1.11.1.min.js" type="text/javascript"></script>
<script src="http://code.jquery.com/ui/1.11.0/jquery-ui.min.js" type="text/javascript"></script>

<!--Theme-->
<link href="http://cdn.wijmo.com/themes/aristo/jquery-wijmo.css" rel="stylesheet" type="text/css" />

<!--Wijmo Widgets CSS-->
<link href="http://cdn.wijmo.com/jquery.wijmo-pro.all.3.20142.45.min.css" rel="stylesheet" type="text/css" />

<!--Wijmo Widgets JavaScript-->
<script src="http://cdn.wijmo.com/jquery.wijmo-open.all.3.20142.45.min.js" type="text/javascript"></script>
<script src="http://cdn.wijmo.com/jquery.wijmo-pro.all.3.20142.45.min.js" type="text/javascript"></script>
<script src="http://cdn.wijmo.com/interop/wijmo.data.ajax.3.20142.45.js" type="text/javascript"></script>
{% endblock %}

{% block content %}
    <div id="chart">
    </div>
    {{ chart.title }}
    {{ chart.get_type_display }}
    {% for series in chart.series.all %}
        {{ series.column }}
    {% endfor %}
        <div>
            Chart options:
            {{ chart.options|jsonify|safe }}
        </div>
{% endblock content %}

{% block scripts %}
<script type="text/javascript">
    $(document).ready(function() {
        $.get("{% url 'chart-data-orient' pk=chart.data.id orient='columns' %}", function(data) {
            var map = {};
            var cols = {};
            {% for series in chart.series.all %}
            cols['{{ series.column }}'] = '{{ series.axis }}';
                {% if series.axis == 'x' %}
            cols['x'] = '{{ series.column }}';
                {% endif %}
            {% endfor %};
            for (var column in data) {
                map[column] = new Array();
                for (var item in data[column]) {
                    map[column].push(data[column][item]);
                }
            }
            $("#chart").wij{{ chart.get_type_display|lower }}chart({
                autoResize: "true",
                {% if chart.type == "P" %}
                radius: {{ chart.options.radius }},
                {% endif %}
                {% if chart.type == "L" or chart.type == "B" %}
                axis:
                    { y : { text : "Y-axis" },
                      x : { text : "X-axis" }
                    }
                ,
                horizontal: false
                ,
                {% endif %}
                header: { text: "{{ chart.title }}" },
                seriesList: [
                {% for series in chart.series.all %}
                    {% if series.axis != "x" %}
                    {
                        label: "{{ series.column }}",
                        labelEntry: true,
                        data: { x : map[cols['x']], y: map['{{ series.column }}'] }
                    },
                    {% endif %}
                {% endfor %}
                ]
            });
        }).fail(function() {
            alert("There was an error fetching the data");
        });
    });
</script>
{% endblock %}

graph/templates/api/spreadsheet_detail.html
{% extends 'base.html' %}

{% block extra_head %}
<!--Theme-->
<link href="http://cdn.wijmo.com/themes/aristo/jquery-wijmo.css" rel="stylesheet" type="text/css" />

<!--Wijmo Widgets CSS-->
<link href="http://cdn.wijmo.com/jquery.wijmo-pro.all.3.20142.45.min.css" rel="stylesheet" type="text/css" />

<!--Wijmo Widgets JavaScript-->
<script src="http://cdn.wijmo.com/jquery.wijmo-open.all.3.20142.45.min.js" type="text/javascript"></script>
<script src="http://cdn.wijmo.com/jquery.wijmo-pro.all.3.20142.45.min.js" type="text/javascript"></script>
<!--SpreadJS Widgets JavaScript-->
<script src="http://cdn.wijmo.com/spreadjs/jquery.wijmo.wijspread.all.3.20142.11.min.js" type="text/javascript"></script>

<!--SpreadJS Widgets CSS-->
<link href="http://cdn.wijmo.com/spreadjs/jquery.wijmo.wijspread.3.20142.11.css" rel="stylesheet" type="text/css" />

<!--Wijmo Ajax Data-->
<script src="http://cdn.wijmo.com/interop/wijmo.data.ajax.3.20142.45.js" type="text/javascript"></script>

<!--Knockout JS Library-->
<!-- Both of the links below can work -->
<script src="http://cdn.wijmo.com/wijmo/external/knockout-2.2.0.js" type="text/javascript"></script>
<!--<script src="http://cdn.wijmo.com/amd-js/3.20142.45/knockout-3.1.0.js" type="text/javascript"></script>-->

<!--Wijmo Knockout Integration Library-->
<script src="http://cdn.wijmo.com/interop/knockout.wijmo.3.20142.45.js" type="text/javascript"></script>

<style type="text/css">
ul.series-fields {
    padding-left: 0px;
}
ul.series-fields li { display: inline; }
</style>
{% endblock %}

{% block content %}
<h1>Spreadsheet <small class="text-right"><button type="button" class="btn btn-small btn-primary" id="btn-wizard">Chart Wizard</button> </small></h1>
    <table id="sheet-grid" data-bind="wijgrid: {
        data: sheet,
        allowEditing: true,
        allowPaging: true,
        showFilter: true }">
    </table>
    <div id="dialog-chart" title="Chart Wizard">
        <form id="chart-form" action="{% url 'chart-create' %}" method="post" class="form-horizontal form-inline">
        {% csrf_token %}
        <legend>Options</legend>
        {{ chart_form.as_p }}
        {{ formset.management_form }}
        <legend>Series</legend>
        {% for chartseries_form in formset %}
            <div id="chartseries-{{ forloop.counter0 }}">
                <ul class="series-fields">
                {{ chartseries_form.as_ul }}
                </ul>
            </div>
        {% endfor %}
        <div class="form-actions">
            <button type="button" class="btn btn-info add-series">Add Series</button>
            <button type="submit" class="btn btn-default">Create Chart</button>
        </div>
        </form>
    </div>
{% endblock content %}

{% block scripts %}
<script type="text/javascript">
var view;

function ViewModel() {
    this.sheet = new wijmo.data.AjaxDataView("{% url 'chart-data' pk=sheet.id%}",
        {
            onResponse: function(response) {
                return {
                    totalItemCount: response.length,
                    results: response
                }
            },
            allowFiltering: false,
            allowPaging: false
        }
    );
}

$(function() {
    view = new ViewModel();
    ko.applyBindings(view);
    $("#dialog-chart").wijdialog({
        autoOpen: false,
        modal: true,
        resizeable: false,
        width: 600,
        height: 480,
        captionButtons: {
            pin: { visible: false },
            refresh: { visible: false },
            toggle: { visible: false },
            minimize: { visible: false },
            maximize: { visible: false }
        },
        buttons: [
            { text: "OK", click: function(e) { $("#chart-form").submit() }},
            { text: "Cancel", click: function() { $(this).wijdialog('close')}}
        ],
        open: function() {

        }
    });
    $("#btn-wizard").click(function() {
        $("#dialog-chart").wijdialog('open');
    });
});

</script>
{% endblock %}

graph/templates/api/spreadsheet_list.html
{% extends 'base.html' %}

{% block content %}
<h1>Spreadsheets<small class="text-right">
<a href="{% url 'spreadsheet-upload' %}">
<button type="button" class="btn btn-small btn-default"><i class="fa fa-plus"></i>Add Sheet</button>
</a>
</small></h1>
<ul>
{% for sheet in sheets %}
    <li><a href="{% url 'spreadsheet-detail' pk=sheet.id %}">{{ sheet.file.name }}</a></li>
{% endfor %}
</ul>
{% endblock content %}